from challenges import day_3

test_input = '''467..114..
                ...*......
                ..35..633.
                ......#...
                617*......
                .....+.58.
                ..592.....
                ......755.
                ...$.*....
                .664.598..'''

test_list = test_input.split("\n")

test_dict = {k:test_list[k].strip() for k in range(0,10)}
